Filtering output plots for:
d_vulg e_coli e_fae e_limo k_pneum m_smeg


Removing existing data
Filtering plots for d_vulg
Finished filtering outputs for d_vulg into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/d_vulg/plots/
----------------------------------------------------

Removing existing data
Filtering plots for e_coli
Finished filtering outputs for e_coli into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/
----------------------------------------------------

Removing existing data
Filtering plots for e_fae
srun: Job 26075156 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 26075156
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/.conda/envs/tart/bin/tart-targeted", line 33, in <module>
    sys.exit(load_entry_point('bio-tart', 'console_scripts', 'tart-targeted')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 194, in exec_main
    main(
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 332, in main
    peak_log, cluster_stats = Cluster(pd.DataFrame(log)).get()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 22, in __init__
    self.df = self.__cluster(peak_log)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 45, in __cluster
    tdf["cluster"] = clfunc()
                     ^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 120, in wrapper
    return fclusterdata(X, t=0.04, criterion="distance", method="complete")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 2704, in fclusterdata
    Z = linkage(Y, method=method)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 1067, in linkage
    n = int(distance.num_obs_y(y))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/spatial/distance.py", line 2630, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
Finished filtering outputs for e_fae into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_fae/plots/
----------------------------------------------------

Removing existing data
Filtering plots for e_limo
srun: Job 26075156 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 26075156
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/.conda/envs/tart/bin/tart-targeted", line 33, in <module>
    sys.exit(load_entry_point('bio-tart', 'console_scripts', 'tart-targeted')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 194, in exec_main
    main(
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 332, in main
    peak_log, cluster_stats = Cluster(pd.DataFrame(log)).get()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 22, in __init__
    self.df = self.__cluster(peak_log)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 45, in __cluster
    tdf["cluster"] = clfunc()
                     ^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 120, in wrapper
    return fclusterdata(X, t=0.04, criterion="distance", method="complete")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 2704, in fclusterdata
    Z = linkage(Y, method=method)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 1067, in linkage
    n = int(distance.num_obs_y(y))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/spatial/distance.py", line 2630, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
Finished filtering outputs for e_limo into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_limo/plots/
----------------------------------------------------

Removing existing data
Filtering plots for k_pneum
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: divide by zero encountered in scalar divide
  W = numer / denom
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: divide by zero encountered in scalar divide
  W = numer / denom
Finished filtering outputs for k_pneum into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/k_pneum/plots/
----------------------------------------------------

Removing existing data
Filtering plots for m_smeg
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/.conda/envs/tart/bin/tart-targeted", line 33, in <module>
    sys.exit(load_entry_point('bio-tart', 'console_scripts', 'tart-targeted')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 194, in exec_main
    main(
  File "/users/PDS0325/sachitk26/packages/tart/tart/targeted/filter_BAM_plots.py", line 332, in main
    peak_log, cluster_stats = Cluster(pd.DataFrame(log)).get()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 22, in __init__
    self.df = self.__cluster(peak_log)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 45, in __cluster
    tdf["cluster"] = clfunc()
                     ^^^^^^^^
  File "/users/PDS0325/sachitk26/packages/tart/tart/utils/cluster.py", line 120, in wrapper
    return fclusterdata(X, t=0.04, criterion="distance", method="complete")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 2704, in fclusterdata
    Z = linkage(Y, method=method)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 1067, in linkage
    n = int(distance.num_obs_y(y))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/spatial/distance.py", line 2630, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
Finished filtering outputs for m_smeg into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/m_smeg/plots/
----------------------------------------------------

Done
