Filtering output plots for:
b_sub_168


Removing existing data
Filtering plots for b_sub_168
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: invalid value encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: divide by zero encountered in scalar divide
  W = numer / denom
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: divide by zero encountered in scalar divide
  W = numer / denom
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: divide by zero encountered in scalar divide
  W = numer / denom
Finished filtering outputs for b_sub_168 into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/b_sub_168/plots/
----------------------------------------------------

Done
